### ISSUE TITLE
触摸板不能使用

### ISSUE THREAD

**Issue by kik1o** [czy1024/XiaoXin-Air15-IKBR-2018-EFI#1]
触摸板不工作。
usb共享网络无反应。
其余功能正常。
谢谢大佬分享！
10.15.7  19H15

**Comment by Mering** [comment]
10.15.7 19H15

**Comment by kik1o** [comment]
把触摸驱动重新放进了clover
用了通用的intel的wifi和蓝牙驱动
基本完美了
不知道big sur能不能这么搞

**Comment by lunasaw** [comment]
目前我还没升级，cv应该生不了，你可以直接OTG升级试试，记得做好备份

**Comment by kik1o** [comment]
> 目前我还没升级，cv应该生不了，你可以直接OTG升级试试，记得做好备份

直接关闭盖子后里屏幕就不亮了，有啥办法吗
